### PR TITLE
Atom

### PR DESCRIPTION
**Pull request by thauti**
Adding the Atom Editor

### CODE REVIEW

**Comment by Justinzobel** [comment]
Well it certainly builds and works, howere there is instructions to build from source which would be preferred. https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md

**Comment by thauti** [comment]
Well, yesterday Strangely I could not compile it. But now it works normally.
I'll fix it.

**Comment by thauti** [comment]
I just saw https://github.com/evolve-os/repository/pull/16 any news ?

**Comment by Justinzobel** [comment]
I commented there also but that package was built via a deb. Please submit one as per the comments in #16.

**Pull request closed without merging**
